development:
  adapter: postgresql
  encoding: unicode
  database: venuerific
  username: admin
  password: root
test:
  adapter: postgresql
  encoding: unicode
  database: venuerific_test
  username: admin 
  password: root

