development:
  adapter: postgresql
  encoding: unicode
  database: venuerific
  username: admin
  password: root
test:
  adapter: postgresql
  encoding: unicode
  host:  <%= ENV['POSTGRES_HOST'] %>
  database: <%= ENV['POSTGRES_DB'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>